// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BasicMemoryDataPoint.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SolarWinds.UniversalPolling.Prototyping.HwhMonitoringLogic.Protobuf {

  /// <summary>Holder for reflection information generated from BasicMemoryDataPoint.proto</summary>
  public static partial class BasicMemoryDataPointReflection {

    #region Descriptor
    /// <summary>File descriptor for BasicMemoryDataPoint.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BasicMemoryDataPointReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpCYXNpY01lbW9yeURhdGFQb2ludC5wcm90bxJDU29sYXJXaW5kcy5Vbml2",
            "ZXJzYWxQb2xsaW5nLlByb3RvdHlwaW5nLkh3aE1vbml0b3JpbmdMb2dpYy5Q",
            "cm90b2J1ZiJmChRCYXNpY01lbW9yeURhdGFQb2ludBITCgtUb3RhbE1lbW9y",
            "eRgBIAEoARISCgpVc2VkTWVtb3J5GAIgASgBEg8KB0lzRXJyb3IYAyABKAgS",
            "FAoMRXJyb3JNZXNzYWdlGAQgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SolarWinds.UniversalPolling.Prototyping.HwhMonitoringLogic.Protobuf.BasicMemoryDataPoint), global::SolarWinds.UniversalPolling.Prototyping.HwhMonitoringLogic.Protobuf.BasicMemoryDataPoint.Parser, new[]{ "TotalMemory", "UsedMemory", "IsError", "ErrorMessage" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BasicMemoryDataPoint : pb::IMessage<BasicMemoryDataPoint> {
    private static readonly pb::MessageParser<BasicMemoryDataPoint> _parser = new pb::MessageParser<BasicMemoryDataPoint>(() => new BasicMemoryDataPoint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BasicMemoryDataPoint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SolarWinds.UniversalPolling.Prototyping.HwhMonitoringLogic.Protobuf.BasicMemoryDataPointReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BasicMemoryDataPoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BasicMemoryDataPoint(BasicMemoryDataPoint other) : this() {
      totalMemory_ = other.totalMemory_;
      usedMemory_ = other.usedMemory_;
      isError_ = other.isError_;
      errorMessage_ = other.errorMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BasicMemoryDataPoint Clone() {
      return new BasicMemoryDataPoint(this);
    }

    /// <summary>Field number for the "TotalMemory" field.</summary>
    public const int TotalMemoryFieldNumber = 1;
    private double totalMemory_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double TotalMemory {
      get { return totalMemory_; }
      set {
        totalMemory_ = value;
      }
    }

    /// <summary>Field number for the "UsedMemory" field.</summary>
    public const int UsedMemoryFieldNumber = 2;
    private double usedMemory_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double UsedMemory {
      get { return usedMemory_; }
      set {
        usedMemory_ = value;
      }
    }

    /// <summary>Field number for the "IsError" field.</summary>
    public const int IsErrorFieldNumber = 3;
    private bool isError_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsError {
      get { return isError_; }
      set {
        isError_ = value;
      }
    }

    /// <summary>Field number for the "ErrorMessage" field.</summary>
    public const int ErrorMessageFieldNumber = 4;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BasicMemoryDataPoint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BasicMemoryDataPoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TotalMemory, other.TotalMemory)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UsedMemory, other.UsedMemory)) return false;
      if (IsError != other.IsError) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TotalMemory != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TotalMemory);
      if (UsedMemory != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UsedMemory);
      if (IsError != false) hash ^= IsError.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TotalMemory != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TotalMemory);
      }
      if (UsedMemory != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(UsedMemory);
      }
      if (IsError != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsError);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ErrorMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TotalMemory != 0D) {
        size += 1 + 8;
      }
      if (UsedMemory != 0D) {
        size += 1 + 8;
      }
      if (IsError != false) {
        size += 1 + 1;
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BasicMemoryDataPoint other) {
      if (other == null) {
        return;
      }
      if (other.TotalMemory != 0D) {
        TotalMemory = other.TotalMemory;
      }
      if (other.UsedMemory != 0D) {
        UsedMemory = other.UsedMemory;
      }
      if (other.IsError != false) {
        IsError = other.IsError;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            TotalMemory = input.ReadDouble();
            break;
          }
          case 17: {
            UsedMemory = input.ReadDouble();
            break;
          }
          case 24: {
            IsError = input.ReadBool();
            break;
          }
          case 34: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
