version: '3'

services:

  #to run multiple instances: docker-compose up --scale cache_consumer=3
  cache_consumer:
    build: .
    environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    links:
      - "redis:sharedCache"

  redis:
    image: redis:4.0.5-alpine
    hostname: sharedCache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
        - "6379:6379"
    #volumes:
    #    - ./redis.conf:/usr/local/etc/redis/redis.conf
        
